### ISSUE TITLE
HDMI audio is broken?

### ISSUE THREAD

**Issue by gfoury** [gfoury/UX305FA-DSDT-Patch#2]
SSDT-HACK.aml is missing `_SB.PCI0.IGPU._DSM` and `_SB.PCI0.HDAU._DSM` methods, and those are probably necessary for AppleHDA to output sound on HDMI.

**Comment by Richie765** [comment]
I updated the driver to fix the audio, but now the video seems to be broken. It works for a second, then black screen, then static and then works again for a second.

**Comment by gfoury** [comment]
When does this happen? When you plug HDMI in, the external HDMI gets black screen then static then black screen? 

What is happening to internal video?

Do you have another HDMI monitor you could try this with? The static could be HDCP failure.

**Comment by Richie765** [comment]
I checked again, and it seems my cable has connection problems. I didn't notice it before. Not sure if it's on the side of the laptop or the cable. Anyway it's working if I fiddle a bit with it.

**Comment by gfoury** [comment]
Glad it's working. 

I have problems if HDMI is connected on boot, but I am not sure what to do about them….
