### ISSUE TITLE
Investigate spigots's AppleHDA for jack switching

### ISSUE THREAD

**Issue by gfoury** [gfoury/UX305FA-DSDT-Patch#9]
https://bitbucket.org/spigots/ux305-el-capitan has a different AppleHDA. See if it has improved behavior for headphone plug/unplug.

McShmoopy is pretty sure it won't....

**Comment by spigots** [comment]
For what it's worth... it won't. :( VoodooHDA + AppleHDA seem to be working best for me.

**Comment by gfoury** [comment]
OK, thank you for pointing that out. I'll have another look at the combo.
